# Generated by Django 3.1.7 on 2021-03-25 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='dtf',
            field=models.DateTimeField(auto_now=True, verbose_name='DTF'),
        ),
    ]
