# Generated by Django 3.1.7 on 2021-03-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_bookmark_dtf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='dtf',
            field=models.DateTimeField(verbose_name='DTF'),
        ),
    ]
