# Generated by Django 3.1.7 on 2021-03-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0005_bookmark_txf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='txf',
            field=models.TextField(null=True, verbose_name='txf'),
        ),
    ]
