# Generated by Django 3.1.7 on 2021-03-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0007_auto_20210325_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='txf',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='txt',
            field=models.TextField(blank=True, null=True, verbose_name='txt'),
        ),
    ]
