# Generated by Django 3.1.7 on 2021-04-02 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0008_auto_20210329_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='dtf',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='txt',
        ),
    ]
